#![doc = include_str!("../README.md")]

// Allow `::llm_tool::` paths (generated by the `#[llm_tool]` proc macro) to
// resolve when compiling tests within this crate.
extern crate self as llm_tool;

mod registry;
mod rust_tool;
mod types;

pub use registry::*;
pub use rust_tool::*;
pub use types::*;
