#![doc = include_str!("../README.md")]

// Allow `::llm_tool::` paths (generated by the `#[llm_tool]` proc macro) to
// resolve when compiling tests within this crate.
extern crate self as llm_tool;

mod registry;
mod rust_tool;
mod types;

/// Re-export `prompt_templates` so `response_template` generated code can
/// reference `::llm_tool::__prompt_templates::` without requiring the user
/// to add `prompt-templates` as a direct dependency.
#[cfg(feature = "prompt-templates")]
#[doc(hidden)]
pub use prompt_templates as __prompt_templates;
pub use registry::*;
pub use rust_tool::*;
pub use types::*;
